export default {     //export {

    // PROFILES_RECEIVED: 'PROFILES_RECEIVED',
    // PROFILE_CREATED: 'PROFILE_CREATED',
    CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
    // REVIEWS_RECEIVED: 'REVIEWS_RECEIVED',
    // REVIEW_CREATED: 'REVIEW_CREATED', 
    // CAMPS_RECEIVED: 'CAMPS_RECEIVED',
    // CAMP_CREATED: 'CAMP_CREATED'   
}